### ISSUE TITLE
Explain end to bridge encryption things that one should know

### ISSUE THREAD

**Issue by yajo** [YunoHost-Apps/mautrix_telegram_ynh#12]
### Describe the bug

Confusing installation step.

### Context

- Hardware: *Raspberry Pi at home*
- YunoHost version: 4.3.4.2 (stable).
- I have access to my server: *Through webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 0.10.2~ynh3

### Steps to reproduce

- *If the error occurs in your browser, explain what you did:* (well it's not exactly an error)
   1. Fill installation form.
   2. You find this message: https://github.com/YunoHost-Apps/mautrix_telegram_ynh/blob/3271f8767f5f87e30ad7ea6d6d580d09dfa9316f/manifest.json#L69

### Expected behavior

If you expect the user to know something... it should be explained somewhere.

I read the README but couldn't find anything about encryption.

**Comment by thardev** [comment]
Hi 😄 
I added a link to the official E2BE docs from Mautrix to the help prompt, I hope this could make it clearer.
