### ISSUE TITLE
e2be is not configured, like AT ALL

### ISSUE THREAD

**Issue by lenowac** [YunoHost-Apps/mautrix_telegram_ynh#15]
**Problem:** Even though the end to bridge option is enabled, the bridge is not configured correctly. 

You can **reproduce** it by installing the bridge, using the the e2be option and checking the config.yaml. The bot will not work neither and error out with "This bridge is not configured to use encryption"

**Desired goals**
1. install/remove the optional dependencies
2. enable at least the config option to allow encrypted chats. If that works reliably, the “force encryption“ option should be enabled. 

**Changes** that could resolve it:
- add a variable in the config, like it is done with `__SERVER_NAME__` to corrispond to the switch
- install python-olm, pycryptodome and unpaddedbase64

but im not an expert, its more of an educated guess from the mautrx docs and looking at the config scripts. A low effort, imho shitty workaround would be to remove the e2be switch.

**Environment:** VPS with Debian 10 running YH 4.3.5 (stable).

This is the same with other mautrix bridges. See https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/issues/40 and https://github.com/YunoHost-Apps/mautrix_signal_ynh/issues/35

**Comment by benneti** [comment]
this was more of a placeholder, I don't use it anymore but feel free to implement the necessary changes if you have time.

**Comment by lenowac** [comment]
yup, will probably hack away as soon as I have the setup working :)
