### ISSUE TITLE
Still maintained? Need help maintaining it?

### ISSUE THREAD

**Issue by thardev** [YunoHost-Apps/mautrix_telegram_ynh#19]
It seems that new versions came up and some pull requests are stuck for some months.
Could I provide any help in order to maintain this app?
Thanks for the hard work past, present and future :)

**Comment by benneti** [comment]
Hey, I stopped using yunohost a while ago so I have no option to actually test (as in everything not just the build works). 
If you feel up to it you can take it over from my side.

**Comment by benneti** [comment]
To become a maintainer I think you need to ask in one of the https://yunohost.org/en/chat_rooms?q=%2Fchat_rooms
if I need to do something please let me know

**Comment by thardev** [comment]
Hi @benneti, thanks for your answer, I'll try to ask @Gredin67 if he can make me a maintainer like he did in the mautrix_whatsapp project so I'll be glad to take over here as well :)

**Comment by benneti** [comment]
Thats perfect, in the meanwhile you can tell me whether you use any of the PRs already and they work and I'll merge them until you can officially take over.
