### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by Gredin67** [YunoHost-Apps/mautrix_telegram_ynh#2]
@benneti I am getting following error at install, any clue?
*https://paste.yunohost.org/raw/axuniqutav

**Comment by benneti** [comment]
COuld you try whether the pip commands work in some dorectory (using root like the installer does).
It seems like pip does not like that HOME is not set.
If it also happens without the script we might need to report it upstream.

**Comment by Gredin67** [comment]
I manage to install mautrix_signal_ynh and the install steps are pretty much the same. Thus I suspect an error in the config file. 

Did the package work for you? With what config? Depending on this it could be upstream related, but I don't think so because it is very active. Maybe we should try 0.9.0 rather than the RC

**Comment by benneti** [comment]
0.9 fails to install right now because one depemdemcy package was not pinned and got incompatible with an update, i don't want to fix this manually so i would prefer to keep on the rc.
For me the log looks like it fails in the pip steps, which are independent of the configuration, but maybe I misread the logs. 

Do the pip steps work on their own?
I have this package installed and as far as i understand it also worked for someone else according to the comments in the PR.

**Comment by benneti** [comment]
you could try with the new version if you want

**Comment by benneti** [comment]
because the upgrade script was broken (hopefully fixed now) i just reinstalled and it works

**Comment by Gredin67** [comment]
indeed it works :)

**Comment by benneti** [comment]
great!

**Comment by kuba-orlik** [comment]
I'm experiencing the same issue now: https://paste.yunohost.org/raw/silezebudu

**Comment by benneti** [comment]
with which user do you run the install script and does this user have his $HOME set

**Comment by kuba-orlik** [comment]
I'm running this via the web panel, so not sure what user is running that on the server 🤔

**Comment by benneti** [comment]
also I think this is a problem with pip and I do not understand why it complains about a missing $HOME when there should be nothing done in home. 

Ah this could be the problem, but I have no Idea how to fix it, you can however try to install it via ssh, please report if it works there

**Comment by kuba-orlik** [comment]
huh. works when installed via CLI 🤔

**Comment by kuba-orlik** [comment]
Thanks for being so responsive!

**Comment by benneti** [comment]
No problem, I will leave this open until HOME being set is no longer required!

**Comment by SpiderOnTheNet** [comment]
Hi YunoHoster's !

As admin in home directory, I tried to install it via ssh on my RPI after cloning the repo by using :
`gh repo clone YunoHost-Apps/mautrix_telegram_ynh`

I executed the intall script by using :
```
cd mautrix_telegram_ynh/scripts/
sudo ./install
```

But I got again this variable error :
`./install: line 27: YNH_APP_ARG_SYNAPSENUMBER: unbound variable`

Did I miss something ?

Thanks

**Comment by benneti** [comment]
please try to install it via yunohost command:
sudo yunohost app install mautrix_telegram

**Comment by SpiderOnTheNet** [comment]
It's working !
You are my hero <3

**Comment by benneti** [comment]
no problem
