### ISSUE TITLE
Yunohost 11 - bullseye working?

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/mautrix_telegram_ynh#25]
Could you tell me if this bridge is working under Yunogost 11 - bullseye?
I'm listing all matrix bridges available on Yunohost in here : https://github.com/YunoHost-Apps/synapse_ynh/issues/170
If it is working I'd tick it in the list.
Best regards,

**Comment by thardev** [comment]
Hi @Thatoo :)

Yes, Yunohost 11 on Bullseye should be working, I'm using it on daily basis in my production box.
Best regards!

**Comment by Thatoo** [comment]
I have added a tick then
