### ISSUE TITLE
Service mautrix_telegram fails to start

### ISSUE THREAD

**Issue by rizzek** [YunoHost-Apps/mautrix_telegram_ynh#32]
### Describe the bug
Service "mautrix_telegram" fails to start

### Context

- Hardware: ZBOX PRO ci329 nano
- YunoHost version: 11.0.9.14 (stable)
- I have access to my server: Through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using package version/branch: 0.12.0~ynh1

### Steps to reproduce
Not sure if reproducible, but:
- Installed latest mautrix_telegram via webadmin
- Upgraded YunoHost to latest version 11.X
- Service "mautrix_telegram" failed to start
- Uninstalled and reinstalled latest version of mautrix_telegram
- Service started successfully again
- Rebooted System -> Service mautrix_telegram failed again
- Tried to Restart service via webadmin -> failed

### Expected behavior
The mautrix_telegram service restarts successfully when rebooting or when clicking the "Restart" button in the Services webadmin page.

### Logs
https://pastebin.com/Z1094U1E
(YunoPaste was not working due to CORS settings)

**Comment by thardev** [comment]
Yes, it seems to be the case, so I guess the Postgres db is not setup correctly.
When did you do the reinstall? Because recently, like 9 days ago, a big refactor was done in the install script and if you tried reinstalling before that refactor some unexpected error could had happened.

Could you try reinstalling one more time please? :)
Maybe before doing it also run `sudo yunohost tools update`

**Comment by rizzek** [comment]
The reinstall failed. I won't share the whole log because the YunoPaste also contains my API secrets.
But when setting up the database it says that the user mautrix_telegram already exists and I should provide its password.

**Comment by thardev** [comment]
Ok, I see... could you try the following:
`sudo --user=postgres PGUSER="postgres" PGPASSWORD="$(cat /etc/yunohost/psql)" psql`

If you can connect (hopefully yes) type `\l` and check if you have an existing `mautrix_telegram` database.
If yes, run the following command to drop it:
`sudo --user=postgres dropdb mautrix_telegram`
Then try reinstalling again 👍

**Comment by rizzek** [comment]
I can't. I'm connected as "admin" (shouldn't I?) and it says 
`Sorry, user admin is not allowed to execute '/usr/bin/psql' as postgres on rizzek.com.`

**Comment by thardev** [comment]
Yes, you are right to be connected as admin but I guess that for this operation we need root privileges or it seems so...
Do you have access to root user?

**Comment by rizzek** [comment]
Well, I was able to` sudo su`.
It worked, there is no mautrix_telegram database.

**Comment by rizzek** [comment]
Should I go ahead and try `sudo --user=postgres dropuser mautrix_telegram`?

**Comment by thardev** [comment]
yes, that could help as well :)

**Comment by rizzek** [comment]
It also failed (because the role "mautrix_telegram" did not exist) but I was able to reinstall mautrix_telegram nevertheless. Maybe the rollback of the install script already tidied up after itself and deleted postgres stuff for mautrix_telegram?

Right now I am able to use the bridge again. 

I also rebooted and it seems like my problem is fixed.

Many thanks for your time and your help, @thardev 👍

**Comment by thardev** [comment]
Great! 😄
I'm glad that you solved it! 👍
