### ISSUE TITLE
ERROR:  column "telegrambot" does not exist

### ISSUE THREAD

**Issue by kuba-orlik** [YunoHost-Apps/mautrix_telegram_ynh#8]
When installing the app via the CLI, an error appears:

```
...
Info: [###################.] > Starting a systemd service...
Warning: ERROR:  column "telegrambot" does not exist
Warning: LINE 1: UPDATE users SET admin = 1 WHERE name = telegrambot;
Warning:                                                 ^
Info: [####################] > Installation of mautrix_telegram completed
Success! Installation completed
```
Even though the script says that the installation is sucessful, I can't view the app in the web panel:

![image](https://user-images.githubusercontent.com/2697916/133798208-ef4aa817-4ab8-46d5-836b-8eff43d38a96.png)

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.2.8.3
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 0.10.1~ynh3

**Comment by benneti** [comment]
you can ignore the column error, I will fix it soon. At somepoint one could set the admin like that but it had no functionality anyway and I think the column to set it was removed.
What do you expect there, the app is only a backend and you can only use it from your matrix instance. I.e. you should now be able to write the telegram bot.

**Comment by kuba-orlik** [comment]
I'd expect there to be for example a button to uninstall or otherwise manage the app, as with all other apps

**Comment by benneti** [comment]
Ah ok, I have no Idea how to do this and I thought it should already be there as it is in the manifest... Maybe restart the yunohost-api serivce via ssh and see whether it shows then?

**Comment by benneti** [comment]
@Gredin67 do you have an Idea about the warning, I think mautrix_whatsapp_ynh does the exact same thing, does it work there reliably?

**Comment by kuba-orlik** [comment]
Restarting the yunohost-api service does not fix for me the issue of the app metadata not appearing after choosing it in the admin panel

**Comment by benneti** [comment]
ok, I don't use the webinterface, so I cannot really help out there

**Comment by Gredin67** [comment]
which warning are you talking about?

**Comment by benneti** [comment]
ah sorry, I am talking about
```
Warning: ERROR:  column "telegrambot" does not exist
Warning: LINE 1: UPDATE users SET admin = 1 WHERE name = telegrambot;
```
which I think is due to https://github.com/YunoHost-Apps/mautrix_telegram_ynh/blob/78e25377746ff6a488614c6ea00b8ce7c7e6d88a/scripts/install#L262 which in turn should be basically the same as in whatsapp and signal,
